
export const EXERCISE_CATEGORIES = [
  "M1: ACTIVACIÓN BIOSENSORIAL",
  "M2: ACTIVACIÓN REACTIVA / NEURO-FÚTBOL",
  "M3: DINÁMICA ESPECÍFICA",
  "M4: EL DESAFÍO COACH vs ALUMNO",
  "M5: RECUPERACIÓN Y RETO DE TORNEO"
];

export const SEED_EXERCISES = [
  // M1: ACTIVACIÓN BIOSENSORIAL
  { name: "Firma Articular Completa", moment: "M1", env: "all", description: "Movilidad sistemática de tobillos a cuello. Ejecución: Realizar círculos suaves con cada articulación, empezando por los tobillos y subiendo hasta el cuello (10 reps por lado)." },
  { name: "Gusano (Inchworms)", moment: "M1", env: "all", description: "Caminata con manos para activar cadena posterior. Ejecución: Desde pie, bajar manos al suelo sin doblar rodillas, caminar hasta plancha alta, y volver caminando con los pies hacia las manos." },
  { name: "Gato-Camello Dinámico", moment: "M1", env: "all", description: "Movilidad rítmica de columna vertebral. Ejecución: En cuadrupedia, arquear la espalda hacia arriba (gato) exhalando, y luego hacia abajo (camello) inhalando, fluyendo con la respiración." },
  { name: "Y-W-T Escapular", moment: "M1", env: "gym", description: "Activación de musculatura estabilizadora de hombro. Ejecución: Tumbado boca abajo o inclinado, formar letras con los brazos (Y, W, T) contrayendo las escápulas con control." },
  { name: "Péndulos de Cadera (Frontal/Lateral)", moment: "M1", env: "field", description: "Liberación de articulación coxofemoral. Ejecución: Apoyado en un poste, balancear una pierna de adelante hacia atrás y de lado a lado, manteniendo el torso estable." },
  { name: "Estocada Mundo (World's Greatest Stretch)", moment: "M1", env: "all", description: "Estiramiento dinámico multi-articular. Ejecución: Estocada profunda, llevar codo al suelo por dentro del pie, rotar torso hacia arriba, y luego estirar ambas piernas." },
  { name: "Rotación Torácica en Quadrupedia", moment: "M1", env: "all", description: "Apertura de caja torácica. Ejecución: En cuadrupedia, mano tras la nuca, llevar codo al brazo contrario y luego abrir hacia el techo siguiendo con la mirada." },
  { name: "Sentadilla Global con Pausa", moment: "M1", env: "gym", description: "Activación de tren inferior y core. Ejecución: Sentadilla profunda con talones apoyados, manos entrelazadas al frente, pausa de 3s abajo para mejorar movilidad." },
  { name: "Puente de Glúteo Unilateral", moment: "M1", env: "gym", description: "Activación específica de glúteo mayor. Ejecución: Tumbado boca arriba, una pierna estirada, elevar cadera con la otra pierna apoyada, apretando el glúteo en el tope." },
  { name: "Burpee de Activación Controlada", moment: "M1", env: "field", description: "Aumento de temperatura corporal central. Ejecución: Burpee fluido pero sin salto explosivo, enfocándose en la transición suave de pie a suelo y viceversa." },

  // M2: ACTIVACIÓN REACTIVA/NEURO-FÚTBOL
  { name: "App Reacción (Colores/Números)", moment: "M2", env: "all", description: "Estímulos cognitivos visuales. Ejecución: Usar la app integrada para tocar el color o número que aparece en pantalla lo más rápido posible." },
  { name: "Sprint Gatillo (Sonido/Visual)", moment: "M2", env: "field", description: "Aceleración ante estímulo externo. Ejecución: El atleta espera en posición de listo; ante un silbato o señal visual, arranca en sprint explosivo por 5-10 metros." },
  { name: "Sombra Coach (Espejo)", moment: "M2", env: "all", description: "Seguimiento de movimientos del entrenador. Ejecución: El atleta se coloca frente al coach y debe replicar cada movimiento lateral, salto o cambio de dirección al instante." },
  { name: "Simon Dice con Balón", moment: "M2", env: "field", description: "Atención y control técnico bajo presión. Ejecución: El coach da comandos ('pie derecho', 'pisa balón', 'vuelta'); el atleta ejecuta solo si se dice 'Simon dice'." },
  { name: "Caza-Sombras", moment: "M2", env: "field", description: "Duelo de agilidad y persecución ligera. Ejecución: Un atleta intenta seguir la trayectoria exacta del otro a 1 metro de distancia, reaccionando a cada cambio de ritmo." },
  { name: "Salto al Lazo (Ritmos Variable)", moment: "M2", env: "restricted", description: "Frecuencia de pies y coordinación. Ejecución: Saltar la cuerda variando la velocidad: 20s lento, 10s sprint de pies, buscando reactividad de tobillos." },
  { name: "Escalera de Tiza (Patrones Neuro)", moment: "M2", env: "restricted", description: "Coordinación oculo-pédica en asfalto. Ejecución: Realizar secuencias complejas (dentro-dentro, fuera-fuera) en una escalera dibujada, sin mirar los pies." },
  { name: "Slalom Tenis con Mano", moment: "M2", env: "restricted", description: "Agilidad lateral usando pelota pequeña. Ejecución: Esquivar obstáculos laterales mientras se bota o se lanza una pelota de tenis con una mano, alternando." },
  { name: "Equilibrio BOSU + Pase", moment: "M2", env: "gym", description: "Propiocepción y técnica básica. Ejecución: Mantenerse sobre el BOSU en un pie mientras se recibe y devuelve un pase con el borde interno del pie libre." },
  { name: "Sprint Tarjetas (Rojo/Verde)", moment: "M2", env: "field", description: "Toma de decisiones en velocidad. Ejecución: Correr hacia el coach; si muestra tarjeta verde sigue, si muestra roja debe retroceder en skipping." },

  // M3: DINÁMICA ESPECÍFICA
  { name: "Pases 2:1 Rebotador", moment: "M3", env: "field", description: "Método 2:1: Dos toques control, uno pase. Ejecución: Contra una pared o compañero, recibir con un toque de control orientado y devolver al primer toque." },
  { name: "Control en L + Giro", moment: "M3", env: "field", description: "Técnica de desmarque en espacios reducidos. Ejecución: Recibir balón, arrastrar con la planta haciendo una 'L' y girar 180 grados para salir en conducción." },
  { name: "Remate con Banda Elástica", moment: "M3", env: "field", description: "Potencia de disparo con resistencia. Ejecución: Atar banda a la cintura del pateador; realizar carrera de aproximación y remate luchando contra la tensión." },
  { name: "Volea Pelota Plástica (Precisión)", moment: "M3", env: "restricted", description: "Coordinación de impacto sin peligro. Ejecución: Lanzar pelota plástica al aire y rematar de volea buscando un objetivo pequeño, priorizando el gesto técnico." },
  { name: "Cinturón Pro (Resistencia Sprint)", moment: "M3", env: "field", description: "Fuerza específica en carrera. Ejecución: El coach sujeta el cinturón mientras el atleta intenta sprintear 10m con máxima potencia." },
  { name: "Pase a través de Aros", moment: "M3", env: "field", description: "Precisión de entrega a ras de suelo. Ejecución: Colocar aros en verticales; el atleta debe filtrar pases rasos que pasen exactamente por el centro del aro." },
  { name: "Conducción en 8 (Bordes Int/Ext)", moment: "M3", env: "all", description: "Sensibilidad de contacto con el balón. Ejecución: Trazar un 8 entre dos conos separados por 3m, usando solo el borde externo para girar y el interno para conducir." },
  { name: "Giro 180° tras Pared", moment: "M3", env: "field", description: "Cambio de orientación ofensivo. Ejecución: Dar pase a la pared, recibir de espaldas y girar rápidamente hacia afuera para cambiar el frente de ataque." },
  { name: "Pared y Desmarque de Ruptura", moment: "M3", env: "field", description: "Comprensión táctica de apoyos. Ejecución: Pasar al coach, correr al espacio vacío eliminando una marca imaginaria y recibir el pase de vuelta en carrera." },
  { name: "Anticipación en Estacas", moment: "M3", env: "field", description: "Velocidad de reacción defensiva. Ejecución: Situarse tras una estaca; cuando sale el balón, rodearla rápidamente para interceptar el pase antes que llegue al objetivo." },
  { name: "Sentadilla Búlgara en Banco", moment: "M3", env: "gym", description: "Fuerza unilateral de potencia. Ejecución: Un pie apoyado en banco atrás, bajar cadera verticalmente hasta que la rodilla trasera casi toque el suelo, subir explosivo." },
  { name: "Peso Muerto Rumano", moment: "M3", env: "gym", description: "Fortalecimiento de isquiotibiales. Ejecución: Rodillas ligeramente flexionadas, bajar peso pegado a las piernas llevando la cadera atrás hasta sentir estiramiento en isquios." },
  { name: "Remo en TRX", moment: "M3", env: "gym", description: "Fuerza de tracción y estabilidad de core. Ejecución: Sujetar TRX, inclinar cuerpo atrás, tirar de las manos hacia el pecho manteniendo el cuerpo como una tabla rígida." },
  { name: "Press Pallof (Anti-rotación)", moment: "M3", env: "gym", description: "Estabilidad central clave para el duelo. Ejecución: Banda elástica lateral, empujar manos al frente y sostener evitando que la banda rote el torso hacia el anclaje." },
  { name: "Salto a Caja (Pliometría)", moment: "M3", env: "gym", description: "Potencia de salto vertical. Ejecución: Desde parado, saltar a una caja de 40-60cm aterrizando suave con rodillas flexionadas, bajar caminando." },
  { name: "Swing con Disco/Kettlebell", moment: "M3", env: "gym", description: "Cadena cinética explosiva. Ejecución: Movimiento de bisagra de cadera, lanzar el peso adelante usando la fuerza de glúteos y piernas, no de brazos." },
  { name: "Lanzamiento MedBall Rotacional", moment: "M3", env: "gym", description: "Potencia de núcleo para saques y giros. Ejecución: De lado a una pared, lanzar balón medicinal explosivamente usando la rotación de cadera y abdomen." },
  { name: "Deslizamientos Laterales (Core)", moment: "M3", env: "gym", description: "Fuerza de abductores y estabilidad. Ejecución: Con banda en tobillos o sobre deslizadores, realizar pasos laterales manteniendo tensión y torso erguido." },
  { name: "Plancha sobre Fitball", moment: "M3", env: "gym", description: "Core avanzado inestable. Ejecución: Apoyar antebrazos en fitball y mantener posición de plancha, haciendo pequeños círculos con los codos para mayor reto." },
  { name: "Escaladores (Mountain Climbers)", moment: "M3", env: "all", description: "Resistencia e intensidad metabólica. Ejecución: Posición de plancha, llevar rodillas al pecho alternadamente a máxima velocidad manteniendo la cadera baja." },
  { name: "Sprint Resistido con Banda", moment: "M3", env: "field", description: "Aceleración pura con carga. Ejecución: Atado a banda estática, intentar correr lo más lejos posible manteniendo técnica de carrera (rodillas altas, braceo)." },
  { name: "Saltos en Bancos de Parque", moment: "M3", env: "restricted", description: "Pliometría adaptada al entorno. Ejecución: Usar mobiliario urbano para realizar saltos laterales o frontales, enfocándose en el mínimo tiempo de contacto con el suelo." },
  { name: "Dominadas en Barra", moment: "M3", env: "gym", description: "Fuerza relativa de tren superior. Ejecución: Colgado de barra, tirar hasta que la barbilla pase el nivel de la barra, bajar lento controlando el descenso." },
  { name: "Flexiones Diamante", moment: "M3", env: "all", description: "Fuerza de tríceps y empuje. Ejecución: Manos juntas bajo el pecho formando un diamante con índices y pulgares, bajar hasta tocar manos con el pecho." },
  { name: "Abdominales en V", moment: "M3", env: "all", description: "Potencia abdominal integrada. Ejecución: Boca arriba, elevar simultáneamente torso y piernas rectas para tocar pies con manos, formando una 'V' con el cuerpo." },
  { name: "Step-up Explosivo", moment: "M3", env: "gym", description: "Potencia de arranque por pierna. Ejecución: Un pie en banco, subir con fuerza saltando hacia arriba con la pierna de apoyo, aterrizar y repetir con control." },
  { name: "Remo en Poste/Reja", moment: "M3", env: "restricted", description: "Adaptación de fuerza en entorno común. Ejecución: Sujetar reja con manos, pies cerca de la base, dejarse caer atrás y tirar del cuerpo hacia la reja." },
  { name: "Tríceps en Banco/Silla", moment: "M3", env: "restricted", description: "Fuerza de extensión localizada. Ejecución: De espaldas al banco, manos apoyadas, bajar glúteo al suelo doblando codos y subir extendiendo brazos por completo." },
  { name: "Skipping con Banda en Cintura", moment: "M3", env: "all", description: "Frecuencia gestual bajo tensión. Ejecución: Banda tirando hacia atrás, realizar skipping alto y rápido en el sitio buscando máxima frecuencia de apoyos." },
  { name: "Control y Pase contra Pared", moment: "M3", env: "restricted", description: "Volumen de toques técnicos solo. Ejecución: A 2 metros de una pared, realizar pases continuos: alternar pie derecho e izquierdo, un toque de control y uno de pase." },

  // M4: EL DESAFÍO COACH VS ALUMNO
  { name: "El Francotirador (Derribar Conos)", moment: "M4", env: "field", description: "Puntería de remate competitivo. Ejecución: A linear 5 conos en la línea de meta; el atleta tiene 5 disparos para derribar la mayor cantidad posible." },
  { name: "Bowling de Fútbol", moment: "M4", env: "all", description: "Precisión de pase largo por suelo. Ejecución: Poner botellas o conos a 15m; el atleta debe rodar el balón con el borde interno para tumbar los 'pines'." },
  { name: "El Aro de Fuego (Pasar Balón)", moment: "M4", env: "field", description: "Pase elevado de precisión. Ejecución: El coach sostiene un aro a 1.5m de altura; el atleta debe intentar que el balón pase por dentro haciendo una vaselina." },
  { name: "Canasta en Tacho/Cesta", moment: "M4", env: "all", description: "Sensibilidad de cuchara/globo. Ejecución: Colocar una cesta a 5m; el atleta debe 'embocar' el balón mediante un toque suave de elevación (cuchara)." },
  { name: "Reto del Travesaño", moment: "M4", env: "field", description: "Puntería de larga distancia. Ejecución: Patear desde 20m buscando golpear el travesaño; otorga el doble de puntos si el balón vuelve al pateador." },
  { name: "Tenis-Fútbol (Duelo)", moment: "M4", env: "all", description: "Táctica y técnica de aire. Ejecución: En un espacio de 3x3 con red baja, jugar a pasar el balón sin que toque el suelo más de una vez, a 11 puntos." },
  { name: "El Murito (Pared 1vs1)", moment: "M4", env: "restricted", description: "Duelo de reflejos y control. Ejecución: Coach y atleta frente a una pared compartida; cada uno debe golpear tras el rebote del otro, a un solo toque." },
  { name: "Dominadas Blind (Ojos Cerrados)", moment: "M4", env: "all", description: "Propiocepción técnica extrema. Ejecución: El atleta debe intentar hacer el máximo número de toques (dominadas) con los ojos vendados o cerrados." },
  { name: "El Reloj (Circuito Contrarreloj)", moment: "M4", env: "all", description: "Velocidad bajo presión de tiempo. Ejecución: Realizar un slalom de 5 cones ida y vuelta; el coach toma el tiempo y el atleta busca batir su récord." },
  { name: "Piedra, Papel, Tijera + Sprint", moment: "M4", env: "all", description: "Reacción cognitiva rápida. Ejecución: Jugar PPT frente a frente; el que gana debe sprintear a una zona segura, el otro intenta tocarlo." },
  { name: "La Mancha con Balón", moment: "M4", env: "field", description: "Conducción evasiva competitiva. Ejecución: El coach intenta tocar al atleta, quien debe escapar conduciendo el balón sin salir del área de juego." },
  { name: "Robo de la Cola (Cintas)", moment: "M4", env: "all", description: "Agilidad y cambio de dirección. Ejecución: El atleta lleva una cinta en el pantalón; el coach intenta quitársela mientras el atleta protege mediante movimientos laterales." },
  { name: "Carrera de Cangrejos", moment: "M4", env: "all", description: "Fuerza lúdica y coordinación. Ejecución: Carrera en 4 apoyos (manos y pies, barriga al techo); ideal para fortalecer hombros y core de forma divertida." },
  { name: "El Guardián del Tesoro", moment: "M4", env: "field", description: "Duelo de protección de balón 1vs1. Ejecución: El atleta debe proteger el balón del coach por 15 segundos usando su cuerpo como escudo, sin cometer falta." },
  { name: "El Túnel (Pase entre Piernas)", moment: "M4", env: "field", description: "Habilidad técnica y caño. Ejecución: El coach camina con piernas abiertas; el atleta debe realizar un auto-pase entre las piernas del coach y recuperarlo tras él." },
  { name: "Intocable 2x2 (Posesión)", moment: "M4", env: "field", description: "Juego colectivo de desmarque. Ejecución: Posesión en espacio reducido; si el coach toca a quien tiene el balón, se pierde un punto." },
  { name: "Guerra de Remolque", moment: "M4", env: "gym", description: "Duelo de fuerza de arrastre tracción. Ejecución: Coach y atleta sujetan extremos de una banda; cada uno intenta arrastrar al otro hacia su zona." },
  { name: "Slalom Ciego (Guía de Voz)", moment: "M4", env: "all", description: "Comunicación y confianza técnica. Ejecución: Atleta con ojos cerrados conduce el balón por un circuito, siguiendo solo las instrucciones verbales del coach." },
  { name: "Penal Mareado", moment: "M4", env: "field", description: "Divertimento y equilibrio bajo fatiga. Ejecución: Dar 10 vueltas con la mano en un balón en el suelo y luego intentar patear un penal a arco vacío." },
  { name: "Salto de Longitud del Coach", moment: "M4", env: "restricted", description: "Reto de potencia de salto. Ejecución: Saltar a pies juntos desde una línea; el objetivo es superar la marca dejada anteriormente por el coach." },
  { name: "Duelo de 50 Toques", moment: "M4", env: "all", description: "Resistencia técnica de control. Ejecución: Coach y atleta se pasan el balón de aire; deben completar 50 toques sin que el balón caiga al suelo." },
  { name: "Triple Travesaño", moment: "M4", env: "field", description: "Reto de precisión acumulada. Ejecución: Intentar golpear el travesaño 3 veces consecutivas desde el borde del área." },
  { name: "Sprint Pro contra el Reloj", moment: "M4", env: "field", description: "Test de velocidad máxima. Ejecución: Sprint de 30 metros medido con cronómetro; el atleta tiene 3 intentos para lograr su mejor tiempo." },
  { name: "Plancha de 2 Minutos (Duelo)", moment: "M4", env: "gym", description: "Resistencia isométrica mental. Ejecución: Mantener position de plancha abdominal frente al coach; el que aguante más tiempo gana el reto." },
  { name: "Remate Estético (Chilena/Volea)", moment: "M4", env: "field", description: "Coordinación acrobatica dirigida. Ejecución: El coach lanza centros bombeados; el atleta debe intentar remates acrobáticos espectaculares con seguridad." },
  { name: "Neuro-Tenis con Manos", moment: "M4", env: "restricted", description: "Percepción de trayectorias rápida. Ejecución: Usar pelota de tenis, jugar tenis de mesa en suelo usando las manos como raquetas, estimulando la visión periférica." },
  { name: "Puntería Ciega (Tras Giro)", moment: "M4", env: "all", description: "Orientación espacial pre-remate. Ejecución: Cerrar ojos, girar 3 veces, abrir ojos e inmediatamente rematar a una de las esquinas del arco." },
  { name: "El Circuito Mortal (Habilidades)", moment: "M4", env: "all", description: "Integración de obstáculos diversos. Ejecución: Circuito de zig-zag, salto de valla, conducción y remate final, todo en menos de 15 segundos." },
  { name: "Equilibrio Flamenco (Duelo)", moment: "M4", env: "gym", description: "Estabilidad monopodal competitiva. Ejecución: Parado en un pie con manos en cintura; el atleta debe aguantar sin apoyar el otro pie más tiempo que el coach." },
  { name: "El Pase Maestro (Distancia)", moment: "M4", env: "field", description: "Precisión de pase largo quirúrgico. Ejecución: Intentar poner el balón dentro de un neumático o zona marcada a 30 metros de distancia." },

  // M5: RECUPERACIÓN Y RETO DE TORNEO
  { name: "Salto de Caja de Oro", moment: "M5", env: "gym", description: "Máximo nivel de potencia registrado. Ejecución: Realizar un único salto a la caja más alta alcanzada en el programa, buscando superar el récord histórico." },
  { name: "Control en Pared 1min (Récord)", moment: "M5", env: "restricted", description: "Test de volumen técnico de pases. Ejecución: Máximo número de pases contra pared a un toque en 60 segundos, manteniendo la precisión." },
  { name: "Sentadilla Búlgara Isométrica", moment: "M5", env: "gym", description: "Resistencia muscular final. Ejecución: Mantener la posición baja de la sentadilla búlgara por 45 segundos por pierna, aguantando la quemazón." },
  { name: "Récord de Flexiones (AMRAP)", moment: "M5", description: "Test de fatiga de tren superior. Ejecución: Tantas flexiones de pecho como sea posible con buena técnica hasta que no pueda completar una repetición más." },
  { name: "15 Cabeceos seguidos", moment: "M5", env: "field", description: "Habilidad técnica aérea registrada. Ejecución: Mantener el balón en el aire usando solo la cabeza por 15 toques consecutivos sin que caiga." },
  { name: "Zig-Zag Sin Mirar el Balón", moment: "M5", env: "all", description: "Maestría de conducción periférica. Ejecución: Rodear cones en slalom manteniendo la mirada fija al frente, confiando en el tacto del pie con el balón." },
  { name: "Serie TRX de Enfriamiento", moment: "M5", env: "gym", description: "Vuelta a la calma asistida. Ejecución: Estiramientos dinámicos suaves usando el TRX para mayor rango de movimiento y relajación." },
  { name: "Toque al Punto Más Alto", moment: "M5", env: "gym", description: "Test de alcance vertical máximo. Ejecución: Saltar e intentar tocar una marca en la pared o techo lo más alto posible." },
  { name: "Victoria del Coach (Feedback)", moment: "M5", description: "Evaluación cualitativa de la sesión. Diálogo sobre lo aprendido, puntos de mejora y establecimiento de objetivos para la próxima sesión." },
  { name: "Estiramiento Estático de Cadenas", moment: "M5", description: "Recuperación de longitud muscular. Mantener estiramientos de isquios, cuádriceps, psoas y espalda por 30 segundos cada uno de forma relajada." },
  { name: "Rodillo de Espuma (Foam Roller)", moment: "M5", description: "Liberación miofascial. Rodar sobre las zonas con mayor tensión (piernas, espalda) para masajear y oxigenar el tejido muscular." },
  { name: "Respiración Diafragmática", moment: "M5", description: "Bajada de pulsaciones y relajación. Tumbado boca arriba, inhalar profundamente inflando el abdomen, exhalar lento por la boca para calmar el sistema nervioso." },
  { name: "Masaje de Planta con Pelota", moment: "M5", description: "Recuperación de pies del futbolista. Rodar una pelota de tenis bajo la planta del pie ejerciendo presión suave para relajar la fascia plantar." },
  { name: "Yoga para Futbolistas (Poses)", moment: "M5", description: "Flexibilidad y equilibrio estático. Practicar posturas como 'el perro boca abajo' o 'el guerrero' para estirar integralmente el cuerpo." },
  { name: "Repaso Táctico con Pizarra", moment: "M5", description: "Asimilación cognitiva del entrenamiento. Revisar en una pizarra o tablet las jugadas y conceptos trabajados durante la sesión dinámica." },
  { name: "Check-list de Hidratación", moment: "M5", description: "Hábitos de nutrición deportiva. Consumir agua y electrolitos de forma pautada para asegurar la recuperación líquida tras el esfuerzo." },
  { name: "Medición de Salto Final", moment: "M5", description: "Registro de fatiga neuromuscular. Repetir un salto vertical al final para comparar con el inicio y medir el impacto de la sesión en el sistema." },
  { name: "El Desafío de la Tabla (Core)", moment: "M5", description: "Ranking de resistencia abdominal. Realizar una plancha abdominal perfecta y registrar el tiempo máximo para la tabla de líderes del mes." },
  { name: "Test de Cooper Adaptado 3min", moment: "M5", description: "Capacidad aeróbica final. Correr la máxima distancia posible durante 3 minutos en un recorrido marcado para evaluar el fondo físico." },
  { name: "Selfie del Triunfo (Equipo)", moment: "M5", description: "Fortalecimiento de vínculo Coach-Atleta. Capturar el momento de éxito de la sesión para documentar el progreso y la motivación en redes o app." }
];
