import { useState, useEffect } from 'react';
import { ArrowLeft, Plus, FileText, Loader2, Download, Zap, BarChart3, Activity } from 'lucide-react';
import { db, auth, handleFirestoreError, OperationType } from '../firebase';
import { collection, addDoc, query, where, onSnapshot, orderBy, serverTimestamp } from 'firebase/firestore';
import { generateAthleteReport, AthleteReport } from '../services/reportService';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface ReportsScreenProps {
  onBack: () => void;
  userId: string;
  trainerId: string | null;
}

export const ReportsScreen = ({ onBack, userId, trainerId }: ReportsScreenProps) => {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [isAdding, setIsAdding] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');

  useEffect(() => {
    const q = query(
      collection(db, 'reports'),
      where('userId', '==', userId),
      orderBy('createdAt', 'desc')
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      }));
      setReports(data);
      setLoading(false);
    }, (error) => {
      handleFirestoreError(error, OperationType.LIST, 'reports');
    });

    return () => unsubscribe();
  }, [userId]);

  const handleAdd = async () => {
    if (title && description) {
      try {
        await addDoc(collection(db, 'reports'), {
          title,
          description,
          userId: userId,
          trainerId: trainerId,
          createdAt: serverTimestamp()
        });
        setTitle('');
        setDescription('');
        setIsAdding(false);
      } catch (error) {
        handleFirestoreError(error, OperationType.CREATE, 'reports');
      }
    }
  };

  const handleAutoGenerate = async () => {
    setGenerating(true);
    try {
      const report = await generateAthleteReport(userId);
      if (report) {
        const formattedDesc = `
          PERIODO: ${report.period}
          SESIONES TOTALES: ${report.totalSessions}
          RPE PROMEDIO: ${report.averageRpe.toFixed(1)}
          PUNTUACIÓN CONSISTENCIA: ${report.consistencyScore.toFixed(0)}%
          
          EJERCICIOS MÁS FRECUENTES:
          ${report.topExercises.map(ex => `- ${ex.name} (${ex.count} veces)`).join('\n')}
          
          RESUMEN DE INTELIGENCIA:
          ${report.intelligenceSummary}
        `;

        await addDoc(collection(db, 'reports'), {
          title: `Reporte Automático - ${new Date().toLocaleDateString()}`,
          description: formattedDesc,
          userId: userId,
          trainerId: trainerId,
          createdAt: serverTimestamp(),
          isAutoGenerated: true
        });
      } else {
        alert('No hay suficientes datos para generar un reporte.');
      }
    } catch (error) {
      console.error('Error auto-generating report:', error);
    } finally {
      setGenerating(false);
    }
  };

  const exportToPDF = async (reportId: string) => {
    const element = document.getElementById(`report-${reportId}`);
    if (!element) return;

    try {
      const canvas = await html2canvas(element, {
        backgroundColor: '#000000',
        scale: 2,
        onclone: (clonedDoc) => {
          const elements = clonedDoc.getElementsByTagName('*');
          const canvas = document.createElement('canvas');
          canvas.width = 1;
          canvas.height = 1;
          const ctx = canvas.getContext('2d');
          if (!ctx) return;

          for (let i = 0; i < elements.length; i++) {
            const el = elements[i] as HTMLElement;
            const style = window.getComputedStyle(el);
            const properties = ['backgroundColor', 'color', 'borderColor', 'borderTopColor', 'borderRightColor', 'borderBottomColor', 'borderLeftColor'];

            properties.forEach(prop => {
              const value = (style as any)[prop];
              if (value && (value.includes('oklch') || value.includes('oklab'))) {
                ctx.clearRect(0, 0, 1, 1);
                ctx.fillStyle = value;
                ctx.fillRect(0, 0, 1, 1);
                const [r, g, b, a] = ctx.getImageData(0, 0, 1, 1).data;
                (el.style as any)[prop] = `rgba(${r}, ${g}, ${b}, ${a / 255})`;
              }
            });
          }
        }
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`informe-${reportId}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
    }
  };

  return (
    <div className="min-h-screen bg-black text-white flex flex-col">
      <header className="p-4 border-b border-zinc-800 flex items-center justify-between sticky top-0 bg-black z-10">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-zinc-800 rounded-full transition-colors">
            <ArrowLeft size={24} />
          </button>
          <h1 className="text-xl font-bold">Informes</h1>
        </div>
        <div className="flex gap-2">
          <button 
            onClick={handleAutoGenerate}
            disabled={generating}
            className="bg-zinc-800 text-[#D4AF37] p-2 rounded-full hover:bg-zinc-700 transition-colors disabled:opacity-50"
            title="Generar Automáticamente"
          >
            {generating ? <Loader2 className="animate-spin" size={24} /> : <Zap size={24} />}
          </button>
          <button 
            onClick={() => setIsAdding(true)}
            className="bg-[#D4AF37] text-black p-2 rounded-full hover:bg-[#B8962E] transition-colors"
          >
            <Plus size={24} />
          </button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto p-4">
        {isAdding && (
          <div className="mb-6 p-4 bg-zinc-900 rounded-xl border border-[#D4AF37]/30 space-y-4">
            <input
              type="text"
              placeholder="Título del informe"
              className="w-full bg-black border border-zinc-700 p-3 rounded-lg focus:border-[#D4AF37] outline-none"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
            <textarea
              placeholder="Descripción o notas"
              className="w-full bg-black border border-zinc-700 p-3 rounded-lg focus:border-[#D4AF37] outline-none min-h-[100px]"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
            <div className="flex gap-2">
              <button 
                onClick={handleAdd}
                className="flex-1 bg-[#D4AF37] text-black font-bold py-2 rounded-lg"
              >
                Generar
              </button>
              <button 
                onClick={() => setIsAdding(false)}
                className="flex-1 bg-zinc-800 text-white font-bold py-2 rounded-lg"
              >
                Cancelar
              </button>
            </div>
          </div>
        )}

        {loading ? (
          <div className="flex justify-center py-20">
            <Loader2 className="text-[#D4AF37] animate-spin" size={32} />
          </div>
        ) : (
          <div className="space-y-4">
            {reports.length === 0 ? (
              <div className="text-center py-20 text-zinc-600 italic">
                No hay informes generados
              </div>
            ) : (
              reports.map((item) => (
                <div key={item.id} id={`report-${item.id}`} className="p-6 bg-zinc-900 rounded-3xl border border-zinc-800 shadow-xl relative group overflow-hidden">
                  {item.isAutoGenerated && (
                    <div className="absolute top-0 left-0 w-1 h-full bg-[#D4AF37]"></div>
                  )}
                  
                  <button 
                    onClick={() => exportToPDF(item.id)}
                    className="absolute top-4 right-4 p-2 bg-zinc-800 rounded-lg text-zinc-400 hover:text-[#D4AF37] opacity-0 group-hover:opacity-100 transition-all"
                    title="Exportar a PDF"
                  >
                    <Download size={16} />
                  </button>
                  
                  <div className="flex items-center gap-3 mb-4">
                    <div className={`p-2 rounded-lg ${item.isAutoGenerated ? 'bg-[#D4AF37]/10 text-[#D4AF37]' : 'bg-zinc-800 text-zinc-400'}`}>
                      {item.isAutoGenerated ? <Zap size={18} /> : <FileText size={18} />}
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">{item.title}</h3>
                      <p className="text-[10px] text-zinc-500 uppercase font-bold tracking-widest">
                        {item.createdAt?.toDate ? item.createdAt.toDate().toLocaleDateString() : 'Reciente'}
                      </p>
                    </div>
                  </div>
                  
                  <div className="text-zinc-400 text-sm leading-relaxed whitespace-pre-line">
                    {item.description}
                  </div>

                  {item.isAutoGenerated && (
                    <div className="mt-6 flex gap-4 pt-4 border-t border-zinc-800/50">
                      <div className="flex items-center gap-2">
                        <Activity size={12} className="text-[#D4AF37]" />
                        <span className="text-[10px] text-zinc-500 font-bold uppercase tracking-widest">IA Analizada</span>
                      </div>
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        )}
      </main>
    </div>
  );
};
